language: android
jdk: oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - extra-android-m2repository

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

script:
    - ./gradlew sparklemotion:checkstyle
    - ./gradlew sparklemotion:test
